site_name: APIGear
site_description: lean cycle to discover APIs and drive the product cycle
site_author: JRyannel
copyright: 2020 APIGear UG
google_analytics: ['UA-166716652-4', 'docs.apigear.io']
dev_addr: 0.0.0.0:8080

extra_css:
  - css/extra.css

repo_name: apigear-io/apigear-webdocs
repo_url: https://github.com/apigear-io/apigear-webdocs
theme:
  name: "material"
  palette:
    primary: "indigo"
    accent: "blue"
  font:
    text: "Segoe UI"
    code: "Segoe Mono"
  language: "en"
  features:
    tabs: true
  extra:
    search:
      language: "en"
  nav:
  - Guide:
    - guide/quick-start.md
    - guide/why-apigear.md
    - guide/how-apigear-works.md
    - guide/api-workspace.md
    - guide/faq.md
  - Tutorials:
    - tutorials/qtquick-plugin.md
  - Topics:
    - topics/api-design.md
    - topics/api-mock.md
    - topics/api-codegen.md
  - Reference:
    - reference/idl.md
    - reference/qtcpp-gen.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.magiclink


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/apigear-io
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/apigear
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/apigear
