name: Deploy to Github pages
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npx --yes docusaurus-mdx-checker 
      - run: npm ci
      - run: npm run build

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
